### ISSUE TITLE
[BUG] Missing Criteria Accessor

### ISSUE THREAD

**Issue by EvieTheOwl** [DaFuqs/Revelationary#9]
**Describe the bug**
Crashes on startup. Not entirely sure what's happening here. Using with the following modpack: https://modrinth.com/modpack/stitched

**Mod version**
1.3.5+1.20.1

**Quilt + Fabric versions** 
- QFAPI 7.4.0 with Fabric API 0.90.0 included
- Quilt Loader 0.22.0

**Crash Report**
https://gist.github.com/sleepy-evelyn/44e01ceb67d3c61e8007ba0547673a42

**Comment by EvieTheOwl** [comment]
It's an issue with these `CriteriaAccessors`. https://github.com/DaFuqs/Revelationary/blob/bafd707d803b9cd8c4ac10641bc4cfe3b740f658/src/main/java/de/dafuqs/revelationary/api/advancements/AdvancementCriteria.java#L23

You can replace these with `Criteria.register` I think now. The same issue is present here: https://github.com/DaFuqs/Spectrum/blob/0f458bdb1f26e9f791798f19ac04cc48dc6f4ca2/src/main/java/de/dafuqs/spectrum/progression/SpectrumAdvancementCriteria.java#L45

**Comment by EvieTheOwl** [comment]
It's an issue specifically with Quilt. Tested with Fabric.
Regardless it's probably good practice to not rely on the accessor and instead use the `Criteria` class directly :3

**Comment by EvieTheOwl** [comment]
This is fixed with #10

**Comment by DaFuqs** [comment]
Fix is merged. ✅
Will release an update shortly

**Comment by DaFuqs** [comment]
Release is out for 1.20.1!
1.20.2 changed the way Criteria are registered, to no need to apply this the same fix there.
